version: '3'

services:
  spark:
    image: bitnami/spark:latest
    ports:
      - "7077:7077"  # Spark Web UI
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_PORT_NUMBER=7077
    volumes:
      - ./spark/app:/opt/spark/app 
      - ./JDBC_Driver:/Drivers/SQL_Sever/jdbc

    networks:
      - my_network

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    depends_on:
      - spark
    ports:
      - "8085:8888"
    environment:
      SPARK_MASTER_URL: spark://spark:7077
    networks:
      - my_network
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/
      - ./data:/home/jovyan/work/data/
      - ./JDBC_Driver:/Drivers/SQL_Sever/jdbc

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5442:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  my_network:

volumes:
  postgres_data:
  postgres-db-volume:
